apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: demoapp
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
          envFrom:
            - secretRef:
                name: db-secret
