services:
  backend:
    image: backend:1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container

  frontend:
    image: frontend:1.0.0
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
