apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: demoapp
data:
  default.conf: |
    server {
        listen 80;
        location / {
            proxy_pass http://frontend-service:80;
            proxy_set_header Host $host;
        }
        location /api/ {
            proxy_pass http://backend-service:3000/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
        }
    }
